[package]
name = "ffscripts"
description = "My collection of FFmpeg \"scripts\""
repository = "https://github.com/junapur/ffscripts"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
